### PR TITLE
Iiif av

### LINKED ISSUE #1944: Add IIIF_Av Gem to support audio and video files in the UV
### Descriptive summary

Adds the IIIF_Av gem to support audio and video files in the Universal Viewer

### Rationale

Hyku users would like Audio and Video files to play in the UV

### Expected behavior
Audio and Video files will play in the UV
### Actual behavior
Audio and Video files do not play in the UV
### Steps to reproduce the behavior

1. Create a work with an audio or video attachment
1. View the work show page and observe the UV

### Related work

Link to related tickets or prior related work here.

### PR DESCRIPTION
**Pull request by labradford**
Fixes #1944 

Adds Iiif_Av gem to add UV support for audio and video files

Changes proposed in this pull request:
- Adds IIIF_Av gem
- Updates IIIF_Print gem to latest version (needed for v3 of IIIF manifest)
- Add configuration changes and overrides as needed to get audio and video files working

@samvera/hyku-code-reviewers

### CODE REVIEW

File: app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb [hunk 1]
```diff
@@ -0,0 +1,83 @@
...
+          Request.new(base_url: hostname)
+        end
+
+        def image_content
+          return nil unless latest_file_id
+          url = Hyrax.config.iiif_image_url_builder.call(
+            latest_file_id,
+            request.base_url,
+            Hyrax.config.iiif_image_size_default,
+            object.mime_type
```
[the remark this answers is not in the document]
Comment (alishaevn) [reply app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb:33]: since `object` is the fallback in `#solr_document`, shouldn't we use the result of the method instead? in the event that `super` _does_ apply.

**Review by alishaevn — CHANGES_REQUESTED** [review]

File: app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb [hunk 2]
```diff
@@ -0,0 +1,83 @@
...
+          )
+
+          # Serving up only prezi 3
+          image_content_v3(url)
+        end
+
+        def video_display_content(_url, label = '')
+          width = Array(solr_document.width).first.try(:to_i) || 320
```
Comment (alishaevn) [inline app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb:41]: is there a reason we're wrapping a few values in this file in an array and then calling `.first`, instead of just checking for the presence of the value?

e.g.
``` ruby
# as an array
width = Array(solr_document.width).first.try(:to_i) || 320

# not as an array
width = solr_document.width&.try(:to_i) || 320
```

File: app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb (hunk 1 above)
[the remark this answers is not in the document]
Comment (labradford) [reply app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb]: made suggested changes and tested

File: app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb (hunk 2 above)
Comment (labradford) [reply app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb]: made suggested changes and tested aspect ratio of video uploads

File: app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb [hunk 3]
```diff
@@ -0,0 +1,83 @@
...
+        end
+
+        def audio_display_content(_url, label = '')
+          duration = conformed_duration_in_seconds
+          # rubocop:disable Metrics/LineLength
+          IIIFManifest::V3::DisplayContent.new(Hyrax::IiifAv::Engine.routes.url_helpers.iiif_av_content_url(solr_document.id, label: label, host: request.base_url),
+                                               label: label,
+                                               duration: duration,
+                                               type: 'Sound',
+                                               format: solr_document.mime_type)
```
Comment (bkiahstroud) [inline app/presenters/concerns/hyrax/iiif_av/displays_content_decorator.rb:62]:
```suggestion
          IIIFManifest::V3::DisplayContent.new(
            Hyrax::IiifAv::Engine.routes.url_helpers.iiif_av_content_url(
              solr_document.id,
              label: label,
              host: request.base_url
            ),
            label: label,
            duration: duration,
            type: 'Sound',
            format: solr_document.mime_type
          )
```

File: config/initializers/file_set_derivatives_overrides.rb [hunk 4]
```diff
@@ -1,5 +1,8 @@
 # This file contains overrides to Hyrax::FileSetDerivativesService to increase the size of thumbnails
 
+# @see https://github.com/samvera/hydra-derivatives/blob/main/lib/hydra/derivatives/processors/video/config.rb#L59
+DEFAULT_VIDEO_SIZE = '320x240'
```
Comment (bkiahstroud) [inline config/initializers/file_set_derivatives_overrides.rb:4]: @labradford it looks like this constant is defined outside of any class, making it "global" (i.e. `Object::DEFAULT_VIDEO_SIZE` instead of `Hyrax::...::DEFAULT_VIDEO_SIZE`). Does it have to be?

**Review by bkiahstroud — CHANGES_REQUESTED** [review]

File: config/initializers/file_set_derivatives_overrides.rb (hunk 4 above)
Comment (labradford) [reply config/initializers/file_set_derivatives_overrides.rb]: Checked with Kirk and this was not intentional. I moved it inside the class

**Review by alishaevn — DISMISSED** [review]
